### PR TITLE
Using OpenFL 3.0 (next) rendering system.

### PR DESCRIPTION
**Pull request by Type1J**
After making a good number of pull requests to OpenFL to make it able to support Starling correctly, I've removed the placeholders, and fixed the way that OpenFL TextFields render upstream, so it works correctly on "next" now.

### CODE REVIEW

**Comment by peteshand** [comment]
Awesome, nice work!
Bitmap fonts are currently already working on the html5 target, have you extended this to other platforms?

**Comment by peteshand** [comment]
Just checked your fork and yes bitmap fonts on all playforms! :D Really good stuff. On a side note, I'm not sure if you're an Away3D user as well, but did you see my post on Starling and Away3D Interoperation? http://t.co/VyuzZqnp8f

**Comment by peteshand** [comment]
Just checked your fork and yes bitmap fonts on all playforms! :D Really good stuff. On a side note, I'm not sure if you're an Away3D user as well, but did you see my post on Starling and Away3D Interoperation? http://t.co/VyuzZqnp8f

**Comment by peteshand** [comment]
Only issue I'm now seeing is the cpp target is crashing, I'm on a new PC though, so this might be related to something else. can you confirm the cpp target builds and runs ok on your system.

**Comment by peteshand** [comment]
Looks like the cpp target is falling over in starling.text.TextField when bitmapData.draw(sNativeTextField, drawMatrix); is called. However I'm currently not sure why

**Comment by peteshand** [comment]
I've had to revert the pull request. can you confirm if you are not experiencing the same issue.

**Comment by peteshand** [comment]
FYI I've also replaced the "development" branch with "develop" as this is the standard GitFlow naming conventions.

**Comment by Type1J** [comment]
It's not failing for me. I am using the latest git version of OpenGL and Lime.

**Comment by Type1J** [comment]
I am an Away3D user, and I saw the pull request. That's awesome! Do you have a working Haxe port of Greg's tutorial code for Starling and Away3D interoperability? If so, please make a new repo for it.

**Comment by peteshand** [comment]
Righto, I'll download the latest OpenFL and Lime repos give that a test... however it would be ideal that Starling works with OpenFL and Lime available from Haxelib don't you think.

It's not a one to one port, but it demonstrates to same result. Only issue I have to deal with before I can post source code is there are some robotlegs extensions being used in the example that are currently in private repos.

**Comment by Type1J** [comment]
Running on a haxelib release of OpenFL and Lime is the eventual goal, yes. However, the way that OpenFL and Lime works (in the haxelib version), it will set shaders at strange times during our rendering process. That's because the new renderer uses OpenGL, and it doesn't always clean up correctly. Starling uses some OpenFL renderings (such a in a TextField), and that state change causes Starling to behave poorly. I submitted pull requests to OpenFL to fix those problems, and they have been included. Also, BitmapData in OpenFL is handled differently (It can be premultiplied with alpha, but most of the time it isn't, and it knows if it has been premultipled or not.), and I made pull requests to OpenFL to make Stage3D pay attention to that state, and it has also been accepted. The new Lime was only required because during all of these pulls, Joshua was working on a Cario renderer, and the new OpenFL build expects those files to be present in Lime.

From now on, I'll put the OpenFL changes directly into the pull requests, and I'll submit a second pull request after OpenFL releases those changes to haxelib. Away3D seems to release to haxelib on a much slower cycle than OpenFL and Lime, so you may want to consider adding your changes that you made to it for context sharing here in this repo until the next version is released. I'm sure that there's going to be a new OpenFL release soon with WWX 2015 comming soon, so I'm not going to do that for the OpenFL changes already made.

I think that the eventual goal will be to make it as painless as possible to port an AS3 Starling app to Haxe Starling, and I think that's possible. I know that we made a few changes to the samples to get them to work with OpenFL, but most, if not all, of those changes should be reverted at some point when Haxe Starling can support it.

By the way, once you get this pull working, the stats display (activated by clicking near the bottom on the main menu) doesn't seem to get an update event for frame counting correctly. There's an event that's not being fired correctly in both cpp and Flash. I will get to it eventually, but there are some other OpenFL Stage3D implementation problems that I want to iron out first. You might want to look at it since you were just looking at event stuff.

**Comment by peteshand** [comment]
I've manually pulled over your changes, minus the removal of the OpenFL. 

I've also update the event system, it looks like there were issues with dispatching on the starling stage because of a mistake I'd made during the port, that being said keep an eye on event errors, it wouldn't surprise if I've missed something. 

The stats display now shows when you click the text at the bottom, however the bitmap font looks all messed up in the html5 target... but 100% sure why yet this is happening (flash works fine). 

It also looks like there is an issue in Lime regarding bitmap.setPixels when the byteArray is not long enough to fill the whole bitmapdata... in flash if you pass a byteArray that won't fill the whole bitmapdata this results in only as many pixels in the byteArray being set, so I've made a pull request to the Lime repo to resolve this.

**Pull request merged**
