### PR TITLE
Fixing loop that previously accessed array out of bounds.

### PR DESCRIPTION
**Pull request by Type1J**
This fixes a crash in Flash and native.

Also, the blendMode is what seems to be causing the graphical artifacts. Strangely, both Flash and native seem to report the correct blend modes, but native doesn't have the correct blend behavior. I'm looking into it.

### CODE REVIEW

**Comment by Type1J** [comment]
The blendMode might be caused because OpenFL might not be doing the alpha premultiply when a BitmapData receives pixels.

(This comment really doesn't have anything to do with the pull request, but I'm hesitant to open a new issue because it might be OpenFL that has the problem.)

**Comment by Type1J** [comment]
Ok, now the comments do apply to the pull request. :-) See the commit for details, but it looks like OpenFL/Lime might have to be fixed for this one. I saw a fix that you made for JS for the same problem, but it's fixed in a better place now for all platforms that are not flash (you can now manually create a ConcreteTexture that -is- premultiplied, if you know that that's what you want). When OpenFL does fix this problem, which may be soon (I opened a Lime issue for it), we'll remove the compile time condition, and always use premultipled alpha when getting data from a BitmapData object.

**Comment by Type1J** [comment]
The Tween crashes were due to type errors. Type checking was bypassed by Dynamic in a few places, so the compiler didn't catch them. The .apply() function only works in js and flash, but Reflect.callMethod() does the same thing, and works everywhere. The sample app is looking a ton better on native with lime-hybrid.

**Comment by Type1J** [comment]
On native, it still crashes before you can get into that scene, but at least you can get to it in Flash, and now you can get back from it as well :-).

**Comment by Type1J** [comment]
Native no longer crashes on the Sprite3D scene, and animation continues indefinitely, as the "repeatCount: 0" requests.

**Comment by peteshand** [comment]
Great! All look good, merging now.

**Pull request merged**
